### PR TITLE
visibility of the screen rotation and screen flip icons

### PR DESCRIPTION
**Pull request by AlejandroImbox**
Hello,

I had a problem with the image rotate icons not working properly and I have added that you can modify their visibility to not show them. Also if the screen rotation is enabled (landscape) the image is positioned wrong when rotated, I have also added the possibility to always stay in portrait.

Both ways I have added them of optional form, calling it of the following way

startManualCropper(activity: Activity, inputImageUri: Uri, reqCode: Int, isVisibleRotateIcons:Boolean, orientationPortrait:Boolean)

You would be kind enough to accept the change,

thank you very much,
best regards

### CODE REVIEW

**Comment by hannesa2** [comment]
Thank you !

**Comment by AlejandroImbox** [comment]
Could you release a new version to use the changes?

Thank you

**Comment by AlejandroImbox** [comment]
Sorry I just saw the new version.

Thank you

**Comment by hannesa2** [comment]
https://github.com/hannesa2/CVScanner/releases/tag/1.9

**Pull request merged**
